redis:
  namespace: databases
  replica:
    replicaCount: 0
  auth:
    enabled: true
    existingSecret: redis-secret
    existingSecretPasswordKey: password
  master:
    replicaCount: 1
    containerPorts:
      redis: 6379
    resources:
      limits:
        memory: 250Mi
        cpu: 250m
      requests:
        memory: 250Mi
        cpu: 250m
    persistence:
      storageClass: "redis-sc"
      size: 10Gi

  networkPolicy:
    # Should be enabled later on
    enabled: false
  rbac:
    # Should be enabled
    create: false
  metrics:
    enabled: true
    interval: 20s
    targetPort: metrics
    path: /metrics
