global:
  env: prod
redis:
  namespace: databases
  replica:
    replicaCount: 0
  auth:
    enabled: true
    existingSecret: redis-secret
    existingSecretPasswordKey: password
  master:
    replicaCount: 1
    containerPorts:
      redis: 6379
    resources:
      limits:
        memory: 250Mi
        cpu: 250m
      requests:
        memory: 75Mi
        cpu: 75m
    persistence:
      storageClass: "redis-sc"
      size: 10Gi
      existingClaim: redis-pvc
      enabled: true
    volumeNodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: In
                values:
                  - linux

  networkPolicy:
    # Should be enabled later on
    enabled: false
  rbac:
    # Should be enabled
    create: false
  metrics:
    enabled: true
    interval: 20s
    targetPort: metrics
    path: /metrics
