apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.redis.master.persistence.storageClass }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer